### ISSUE TITLE
Bug if value is undefined or null

### ISSUE THREAD

**Issue by leobernier70** [Delia-Solutions/ts-purerules#18]
must verify if value is NOT undefined or null before checking rule

**Comment by Tiv0w** [comment]
Can you detail your issue ?
What is the use case, and why the TS type system didn't work ?

**Comment by leobernier70** [comment]
For example, if we pass a undefined argument to the function "objectMustNotBeEmpty", it tries to convert to undefined to an array with Object.keys() and throw an error.

**Comment by leobernier70** [comment]
It's the same with every case where we want to process the value like an object (ex: .length, .splice...) or an array
